# Generated by Django 4.2 on 2023-04-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='',
        ),
    ]
