# Generated by Django 4.2.1 on 2023-05-25 13:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_view', '0003_activeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeorder',
            name='order_id',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='order_name', unique=True),
        ),
    ]
