# Generated by Django 4.2.1 on 2023-05-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_view', '0004_activeorder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeorder',
            name='contact',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
